# Generated by Django 3.1.3 on 2022-10-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('languajes', models.TextField(blank=True)),
                ('certificates', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
            ],
        ),
    ]
